version: '3'

services:
  # Web Application with environment and restart policy
  web:
    image: nginx:alpine
    container_name: my-web
    ports:
      - "8080:80"
    environment:
      - SERVER_VERSION=1.0
      - ENV=production
    restart: always
    command: sh -c "echo '<h1>Hello from Nginx!</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    networks:
      - app-network

  # Application with environment variables
  app:
    image: alpine:latest
    container_name: my-app
    environment:
      - APP_NAME=TestApp
      - VERSION=2.1
    restart: unless-stopped
    command: sleep infinity
    networks:
      - app-network

  # Cache service
  redis:
    image: redis:alpine
    container_name: my-redis
    restart: on-failure
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app-network
    ports:
      - "6379"

# Define custom network
networks:
  app-network:
    driver: bridge

# Define persistent volumes
volumes:
  redis_data:
    # Redis data persistence